{% set sonat_version = environ.get('CONDA_SONAT',"0.0.1") %}
{% set vacumm_version = environ.get('CONDA_VACUMM',"3.3.0")|replace(".", "") %}
{% set pkg_buildnum = environ.get('CONDA_BUILDNUM',"0") %}


package:
  name: sonat
  version: "{{ sonat_version }}"

build:
    script: python setup.py install
    string: vc{{ vacumm_version }}_{{ pkg_buildnum }}

source:
  git_url: https://github.com/VACUMM/sonat.git
#  git_rev: {{ sonat_version }}

requirements:
  build:
    - uvcdat >=2.8.0
    - gcc >=4.8.5
    - libsangoma_tools
    - vacumm >=3.3.0
  run:
    - uvcdat >=2.8.0
    - libgcc >=4.8.5
    - libsangoma_tools
    - vacumm >=3.3.0

test:
    requires:
    - nose
    commands:
    - nosetests
    imports:
    - sonat
    - sonat._fcore

about:
  home: https://www.ifremer.fr/sonat
  license: CeCILL-A
  license_file: LICENSE
  summary: Stochastic ocean Observing Network Assessment Toolkit

