{% set sonat_version = environ.get('CONDA_SONAT_VERSION',"0.0.1") %}
{% set pkg_buildnum = environ.get('CONDA_SONAT_BUILDNUM',"1") %}
{% set vacumm_version = environ.get('CONDA_VACUMM_VERSION',"3.3.0")|replace(".", "") %}


package:
  name: sonat
  version: "{{ sonat_version }}"

build:
    script: python setup.py install # --single-version-externally-managed --record record.txt
    string: vc{{ vacumm_version }}_{{ pkg_buildnum }}

source:
  git_url: https://github.com/VACUMM/sonat.git
  git_rev: HEAD
#  git_rev: {{ sonat_version }}

requirements:
  build:
    - uvcdat >=2.8.0
    - vacumm >=3.3.0
    - libsangoma_tools >=2.0.1
    - gcc >=4.8.5
  run:
    - uvcdat >=2.8.0
    - vacumm >=3.3.0
    - libsangoma_tools >=2.0.1
    - libgcc >=4.8.5
    - jinja2

test:
    requires:
    - nose
    #commands:
    #- nosetests $(python -c "import sonat.test;sonat.test.print_test_order()")
    imports:
    - sonat
    - sonat._fcore

about:
  home: https://www.ifremer.fr/sonat
  license: CeCILL-A
  license_file: LICENSE
  summary: Stochastic ocean Observing Network Assessment Toolkit

