{% set sonat_version = environ.get('CONDA_SONAT_VERSION',"0.0.1") %}
{% set pkg_buildnum = environ.get('CONDA_SONAT_BUILDNUM',"1") %}
{% set git_rev = environ.get('CONDA_SONAT_GITREV',sonat_version) %}

package:
  name: sonat
  version: "{{ sonat_version }}"

build:
    script: python setup.py install
    number: {{ pkg_buildnum }}

source:
  git_url: https://github.com/VACUMM/sonat.git
  {% if git_rev!="HEAD" %}
  git_rev: {{ git_rev }}
  {% endif %}

requirements:
  build:
    - uvcdat ==2.8.0
    - vacumm >=3.4.1
    - libsangoma_tools >=2.0.1
    - gcc >=4.7
  run:
    - uvcdat ==2.8.0
    - vacumm >=3.4.1
    - libsangoma_tools >=2.0.1
    - libgcc >=4.7
    - jinja2
    - nose

test:
    commands:
    - sonat info
    - sonat --short-help
    - mkdir -p MYTESTS && cd MYTESTS && sonat --logger-level=debug test
    imports:
    - sonat
    - sonat._fcore

about:
  home: https://relay.actimar.fr/~raynaud/sonat
  license: CeCILL-A
  license_file: LICENSE
  summary: Stochastic ocean Observing Network Assessment Toolkit

