{% set sonat_version = environ.get('CONDA_SONAT_VERSION',"1.1.1") %}
{% set pkg_buildnum = environ.get('CONDA_SONAT_BUILDNUM',"0") %}
{% set git_rev = environ.get('CONDA_SONAT_GITREV',sonat_version) %}

package:
  name: sonat
  version: "{{ sonat_version }}"

build:
    number: {{ pkg_buildnum }}

source:
  git_url: https://github.com/VACUMM/sonat.git
  {% if git_rev!="HEAD" %}
  git_rev: {{ git_rev }}
  {% endif %}

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - libsangoma_tools >=2.0.1
    - pip
  run:
    - {{ pin_compatible('python') }}
    - {{ pin_compatible('numpy') }}
    - vacumm >=3.6.4
    - jinja2
    - nose
    - libnetcdf <=4.7

test:
    commands:
      - sonat info
      - sonat --short-help
      - cd test && make first_failed
    imports:
      - sonat
      - sonat._fcore
    source_files:
      - test/*
      - data/*

about:
  home: https://relay.actimar.fr/~raynaud/sonat
  license: CeCILL-A
  license_file: LICENSE
  summary: Stochastic ocean Observing Network Assessment Toolkit

