{% set sangoma_version = environ.get('CONDA_SANGOMA_VERSION',"2.0.1") %}
{% set pkg_buildnum = environ.get('CONDA_SANGOMA_BUILDNUM',"4") %}

package:
  name: libsangoma_tools
  version: "{{ sangoma_version }}"

build:
  number: {{ pkg_buildnum }}

source:
  url: https://downloads.sourceforge.net/project/sangoma/sangoma-{{ sangoma_version }}.tar.gz
  patches: all.patch

requirements:
  build:
    - {{ compiler('gfortran') }}
  host:
    - fftw
    - lapack
    - libgfortran
  run:
    - fftw
    - lapack
    - libgfortran

about:
  home: http://www.data-assimilation.net
  license: LGPL
  summary: The data assimilation fortran library of the SANGOMA project
